# Generated by Django 5.0.6 on 2024-08-17 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('IdBanco', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NombreBanco', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'banco',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IdCliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NombreCliente', models.CharField(max_length=50)),
                ('DireccionCliente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('IdEmpleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('NombreEmpleado', models.CharField(max_length=30)),
                ('TipoEmpleado', models.BooleanField()),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IdProducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField()),
                ('ValorUnidad', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('IdProveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NombreProveedor', models.CharField(max_length=50)),
                ('DireccionProveedor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('IdFactura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('MedioPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], max_length=50)),
                ('IdBanco', models.ForeignKey(db_column='IdBanco', on_delete=django.db.models.deletion.CASCADE, to='backend.banco')),
                ('IdCliente', models.ForeignKey(db_column='IdCliente', on_delete=django.db.models.deletion.CASCADE, to='backend.cliente')),
                ('IdEmpleado', models.ForeignKey(db_column='IdEmpleado', on_delete=django.db.models.deletion.CASCADE, to='backend.empleado')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='ProductoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('IdFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.factura')),
                ('IdProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.producto')),
            ],
            options={
                'db_table': 'ProductoFactura',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='facturas',
            field=models.ManyToManyField(through='backend.ProductoFactura', to='backend.factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(through='backend.ProductoFactura', to='backend.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='IdProveedor',
            field=models.ForeignKey(db_column='IdProveedor', on_delete=django.db.models.deletion.CASCADE, to='backend.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='productofactura',
            constraint=models.UniqueConstraint(fields=('IdFactura', 'IdProducto'), name='unique_producto_factura'),
        ),
        migrations.AlterUniqueTogether(
            name='productofactura',
            unique_together={('IdFactura', 'IdProducto')},
        ),
    ]
